import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  image: {
    width: "100%",
    height: "100%",
  },
  mainTitle: {
    fontSize: 22,
    textAlign: "center",
    color: "#1d4b26",
    margin: 20,
  },
  title: {
    fontSize: 22,
    textAlign: "center",
    color: "#1d4b26",
    margin: 2,
  },
  checkTitle: {
    fontSize: 22,
    textAlign: "left",
    color: "#1d4b26",
    margin: 2,
  },
  button: {
    borderRadius: 5,
    borderColor: "#1d4b26",
    borderWidth: 2,
    backgroundColor: "#a681ef",
    width: 40,
    height: 40,
  },
  buttonText: {
    color: "#baffc9",
    fontSize: 20,
    textAlign: "center",
    padding: 8,
  },
  textInput: {
    height: 40,
    margin: 10,
    borderWidth: 1,
    borderRadius: 5,
    padding: 10,
    width: 200,
    alignSelf: "center",
    borderColor: "#1d4b26",
    borderWidth: 2,
  },
  container: {
    justifyContent: "space-between",
    alignItems: "center",
  },
  checkBoxLeague: {
    color: "#1d4b26",
    fontSize: 20,
    textAlign: "center",
    padding: 8,
  },
  divider: {
    color: "#1d4b26",
    width: "50%",
    marginTop: 30,
    marginBottom: 30,
    borderWidth: "1px",
    alignSelf: "center",
  },
  listsContainer: {
    backgroundColor: "#cef5bb",
    width: "80%",
    height: "auto",
    justifyContent: "center",
    alignSelf: "center",
    borderRadius: 5,
    paddingTop: 10,
    paddingBottom: 10,
    borderColor: "#1d4b26",
    borderWidth: "1px",
  },
  joinandpendingContainer: {
    backgroundColor: "#e8e8e0",
    width: "80%",
    height: "auto",
    justifyContent: "center",
    alignSelf: "center",
    borderRadius: 5,
    paddingTop: 10,
    paddingBottom: 10,
    borderColor: "#1d4b26",
    borderWidth: "1px",
  },
  return: {
    fontSize: 22,
    textAlign: "center",
    color: "#1d4b26",
    margin: 20,
    marginTop: 70,
    marginBottom: 50,
  },
});

export default styles;
